"""test

Revision ID: ac417602b2c1
Revises: 
Create Date: 2026-02-18 21:37:36.281458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac417602b2c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pairs',
    sa.Column('user_owner_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('user_pair_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('user_owner_complete_test', sa.Boolean(), nullable=False),
    sa.Column('user_pair_complete_test', sa.Boolean(), nullable=False),
    sa.Column('analyze_complete', sa.Boolean(), nullable=False),
    sa.Column('profile_complete', sa.Boolean(), nullable=False),
    sa.Column('passport_complete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('subscription', sa.Enum('FREE', 'BASIC', 'PREMIUM', 'VIP', name='subscriptiontype'), nullable=False),
    sa.Column('ai_question', sa.Integer(), nullable=False),
    sa.Column('subscription_start', sa.DateTime(), nullable=True),
    sa.Column('subscription_end', sa.DateTime(), nullable=True),
    sa.Column('ai_recharge_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('analyzes',
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('block', sa.Integer(), nullable=False),
    sa.Column('analysis_json', sa.JSON(), nullable=True),
    sa.Column('contradictions', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pair_id'], ['pairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passports',
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('passport_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pair_id'], ['pairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passports_pair_id'), 'passports', ['pair_id'], unique=True)
    op.create_table('profiles',
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('user_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profile_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pair_id'], ['pairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_pair_id'), 'profiles', ['pair_id'], unique=True)
    op.create_table('testsessions',
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('block', sa.Integer(), nullable=False),
    sa.Column('questions', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('insight', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('current_block', sa.Integer(), nullable=True),
    sa.Column('total_blocks', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pair_id'], ['pairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testsessions_pair_id'), 'testsessions', ['pair_id'], unique=False)
    op.create_index(op.f('ix_testsessions_telegram_id'), 'testsessions', ['telegram_id'], unique=False)
    op.create_table('subtestsessions',
    sa.Column('test_session_id', sa.Integer(), nullable=False),
    sa.Column('questions', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('insight', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('current_block', sa.Integer(), nullable=True),
    sa.Column('total_blocks', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_session_id'], ['testsessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtestsessions_test_session_id'), 'subtestsessions', ['test_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtestsessions_test_session_id'), table_name='subtestsessions')
    op.drop_table('subtestsessions')
    op.drop_index(op.f('ix_testsessions_telegram_id'), table_name='testsessions')
    op.drop_index(op.f('ix_testsessions_pair_id'), table_name='testsessions')
    op.drop_table('testsessions')
    op.drop_index(op.f('ix_profiles_pair_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_passports_pair_id'), table_name='passports')
    op.drop_table('passports')
    op.drop_table('analyzes')
    op.drop_table('users')
    op.drop_table('pairs')
    # ### end Alembic commands ###
